[book]
authors = ["Garrett D'Amore"]
language = "en"
multilingual = false
src = "src"
title = "NNG Reference Manual"

[output.html]
curly-quotes = true
fold.enable = true
fold.level = 1

[preprocessor.indexing]

[preprocessor.alerts]
