[book]
authors = ["Garrett D'Amore"]
language = "en"
multilingual = false
src = "src"
title = "NNG Reference Manual"

[output.html]
curly-quotes = true
fold.enable = true
fold.level = 1

[preprocessor.indexing]

[preprocessor.indexing.see_instead]

# "*PUSH* (protocol)" = "protocol, *PUSH*"

[preprocessor.indexing.nest_under]
"body" = "message"
"header" = "message"

"*BUS*" = "protocol"
"*PAIR*" = "protocol"
"*PULL*" = "protocol"
"*PUSH*" = "protocol"
"*REQ*" = "protocol"
"*REP*" = "protocol"
"*PUB*" = "protocol"
"*SUB*" = "protocol"
"*SURVEYOR*" = "protocol"
"*RESPONDENT*" = "protocol"

"*inproc*" = "transport"
"*ipc*" = "transport"
"*tls*" = "transport"
"*tcp*" = "transport"
"*ws*" = "transport"
"*wss*" = "transport"

"`inproc://`" = "URI"
"`ipc://`" = "URI"
"`tls+tcp://`" = "URI"
"`tcp://`" = "URI"
"`ws://`" = "URI"
"`wss://`" = "URI"

[preprocessor.alerts]
